### ISSUE TITLE
User Story #3 - Footer

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#10]
As a **user**, I can **see the sites social media links at the bottom of the webpage** so that I can **visit, contact the business and follow them online**.

**Acceptance Criteria**
1. Footer is displayed at bottom of the webpage.
2. Social links visible and open in a new tab.

**Tasks**

- [x] Add footer to base template
- [x] Add social media links
- [x] Add copyright and GitHub info
