### ISSUE TITLE
User Story #4 - Login Page

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#11]
As a **user**, I can **use my email and password to login to my profile account** so that I can **use my profile to connect to the websites features**

**Acceptance Criteria**
1. On clicking the 'Login'(pawprint/key) icon user is brought to the login page.
2. Option to 'Register' available if no prior account.

**Tasks**
- [x] Create Login page
- [x] Link Login icon to Login page
- [x] Create 'Register' link for new users

**Comment by amylour** [comment]
- login now authenticates user using {{ form.as_p }} instead of Tailwind form -> possible solution https://www.accordbox.com/blog/render-django-form-with-tailwind-css-style/

**Comment by amylour** [comment]
- Recreated for FreeFido v2, using Bootstrap5
