### ISSUE TITLE
User Story # 5 - Sign Up/Register Page

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#12]
As a **user**, I can **enter my email and password** so that I can **register an account with the website**.

**Acceptance Criteria**
1. Successful link to the Sign Up page.
2. User registration successfully handled with Django allauth.
3. User is brought to Home page.

**Tasks**

- [x] Create Sign Up page template
- [x] Ensure allauth installed/added to INSTALLED APPS in settings.py/email backend setup
- [x] Connect user registration in urls.py, create Sign Up form for user submission in allauth templates
- [x] Register button brings user to Home page
- [x] Login link in Navbar

**Comment by amylour** [comment]
- After setting up a new repo and workspace (due to issues with previous Database), I have set up my project correctly and am continuing from this point as FreeFido v2
