### ISSUE TITLE
User Story #6 - Profile SetUp feature

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#13]
As a **user**, I can **enter my personal details** so that I can **create an account with FreeFido**.

**Acceptance Criteria**
1. Accessible and easy to use page for user to interact with.
2. Profile form with user details saved successfully in database.
3. User can upload a profile picture and edit their display name and bio.

**Tasks**

- [x] Create Profile SetUp page template
- [x] Set up user profile set up in views.py for submission to database
- [x] Add url path to urls.py

**Comment by amylour** [comment]
- Recreated for FreeFido v2, using Bootstrap5
