### ISSUE TITLE
User Story #7 - Make a Booking page

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#14]
As a **user**, I can **view the booking home page** so that I can **learn about booking and see my active bookings**.

**Acceptance Criteria**
1. Booking information and rules made available to user.
2. If user is logged in, create booking button is visible as are any active bookings.

**Tasks**

- [x] Create booking home page
- [x] Add link to navbar
- [x] Display active bookings for logged in user
- [x] Create link to create booking for logged in user
