### ISSUE TITLE
User Story #8 - Create a Booking feature

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#15]
As a **user**, I can **use the bookings page** so that I can **make a booking at the dog park**.

**Acceptance Criteria**
1. Booking page is accessible by user via booking link.
2. Successful display of user bookings in profile and booking page when logged in.

**Tasks**

- [x]  Confirm user is logged in using allauth
- [x]  Set up authentication for user's bookings to be visible when logged in
- [x] Display active bookings to user
- [x] Inform user via message function that booking has been saved/date&time unavailable
