### ISSUE TITLE
User Story # 12 - Edit User Profile

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#19]
As a **user**, I can **edit my user profile** to **update my personal details**.

**Acceptance Criteria**
1.  'Edit' button brings user to profile edit modal.
2.  User receives visual feedback that the form field areas are ready to be edited.
3.  Form fields prepopulated with users previously saved data.
4.  Database must update with user's new details.

**Tasks**

- [x] Create 'edit' button path
- [x] Create edit profile modal with editable form fields
- [x] Create 'Edit' button connections to push new data to database
