### ISSUE TITLE
Dev Task #2 - Create Django Project

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#2]
As a developer, I can create the Django project and app so that I can set up the database.

** Acceptance Criteria **
1. Create the Django project FreeFido directory
2. Create the booking app
3. PROJ_NAME=freefido APP_NAME=booking

** Tasks **
- [x] Create the Django project FreeFido directory
- [x] Create the booking app
- [x] Add it to the list of INSTALLED_APPS
- [x] Migrate the changes to the database
- [x] Add 8000 port url to ALLOWED_HOSTS
- [x] python3 manage.py runserver to test

**Comment by amylour** [comment]
- Fixed error in creating only one Django app for the three features - booking, userprofile and photo. 
- Created additional apps -> 'userprofile' and 'photo'.
- Adjusted each apps 'models.py' and migrated changes to database.
- Added each app to 'INSTALLED APPS'.

🤞
