### ISSUE TITLE
User Story # 14 - Edit Booking

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#21]
As a **user**, I can **edit my confirmed bookings** so that I **can choose a different day or time slot or add an extra dog**.

**Acceptance Criteria**
1. User can choose the 'Edit' icon button under their viewable bookings when logged in.
2. User can choose from the available dates and times in the calendar to update their booking.
3. Previous booking is released on the calendar when user confirms new booking.
4. Updated booking visible in Active Bookings tabel.

**Tasks**

- [x] Create 'Edit' button
- [x] Create path to edit bookings page
- [x] Edit original booking when user confirms new booking
- [x] Display new booking in 'View Bookings' in Profile and Booking section

**Comment by amylour** [comment]
- Reviewed edit booking feature as alert message was not showing when user tries to book unavailable date. Now added as an alert message via the html template.
- User receives feedback if they 'save', 'delete' or attempt to book an uavailable date.
- Attempted to use 'django-agenda' for displaying and scheduling the available dates. For now this is a 'Could Have' for this project, until my understanding of utilising django packages to manage and display databases and their data grows. I will pursue this learning on a separate development branch.
