### ISSUE TITLE
User Story # 15 - Delete Booking

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#22]
As a **user**, I can **click the 'Trash' icon under my booking** so that I can **delete that booking from my bookings list**.

**Acceptance Criteria**
1.  User can choose the 'Delete' button.
2.  User is prompted to confirm they would like to follow through with the delete confirm page.
3.  Confirm dele button deletes booking and returns user to booking page.

**Tasks**

- [x] Create delete  button
- [x] Create page for deletion confirmation
- [x] Remove booking from users booking list view
