### ISSUE TITLE
Dev Task #8 - SetUp Django allauth

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#23]
As a **developer**, I can **install and setup Django allauth** so that I can **authenticate user accounts**.

**Acceptance Criteria**
1. Successful installation of Django allauth.
2. Successful integration of allauth specifics in settings.py and urls.py

**Tasks**
- [x] Install allauth
- [x] Adjust TEMPLATES in settings.py to include context_processors.request for HTTP request access
- [x] Apply AUTHENTICATION_BACKENDS in settings.py from Django allauth docs for user email login
- [x] Include four apps to INSTALLED APPS - django.contrib.sites, allauth, allauth.account, allauth.socialaccount
- [x] SITE_ID = 1 under AUTHENTICATION_BACKENDS - used in connection with allauth.socialaccount for logging in via social media
- [x] Add allauth accounts url path to project level urls.py
- [x] Migrate new apps

**Comment by amylour** [comment]
- Updated Sites in Django admin to FreeFido in preparation to include social media login
