### ISSUE TITLE
Dev Task #9 - Email authentication setup

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#24]
As a **developer**, I can **use allauth's email authentication backends** so that **I can validate and authorise a user's email for account creation**.

**Acceptance Criteria**
1. Email authentication backends added correctly to settings.py.
2. Requirements.txt updated.

**Tasks**
- [x] Add Email authentication backends from Django allauth docs to settings.py
- [x] Add signup email for admin
- [x] Verify and confirm in Django admin panel
- [x] Add to requirements.txt

**Comment by amylour** [comment]
- Email Verification setup but not tested yet to send out emails to users
- Moved to 'Could Have' label
