### ISSUE TITLE
Dev Task #10 - Tailwind SetUp -> see comment re Bootstrap/Project v2

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#25]
As a **developer**, I can **add and configure Tailwind CSS in my development environment** so that I can **create my website's frontend**.

**Acceptance Criteria**
1. Successful install of Tailwind as per Tailwind docs.
2. Successful configuration of Tailwind in base CSS and HTML files.

**Tasks**

- [x] Install Tailwind following docs
- [x] Configure paths to link Tailwind with base CSS and HTML files
- [x] Complete the Tailwind build process with the correct file paths
- [x] Confirm Tailwind install using 'npm ls'

**Comment by amylour** [comment]
- Fixed Tailwind config issue (fixes detailed in README.MD with doc links)
- Tailwind displaying in index.html

**Comment by amylour** [comment]
- After restarting my project, I have decided to stick with Boostrap 5 for this project to focus on the database learning and development.
