### ISSUE TITLE
Dev Task #3 - Set up Heroku and ElephantSQL

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#3]
As a developer, I can connect my project to use an external database so that my project can be deployed successfully.

** Acceptance Criteria **
1. Successful creation of the Heroku app.
2. Successful creation of the postgreSql database instance.
3. The database is connected to the workspace and to Heroku.

** Tasks **
- [x] Create the app on Heroku
- [x] Create the database instance on ElephantSQL
- [x] Create the env.py file and add to .gitignore
- [x] Modify the settings to connect Django and the env.py and hook up the database
- [x] Protect SECRET_KEY
- [x] Migrate the database structure to the connected ElephantSQL database
- [x] Add Config Vars to Heroku
