### ISSUE TITLE
User Story # 17 - Articles feature setup

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#30]
As a **user**, I want to be able to **post articles to my profile** so that I can **share my experience of the dog park and being a dog owner with others.**

**Acceptance Criteria**
- A user must be able to create a post to be shared to the platform

**Tasks**

- [ ] Create Articles app
- [ ] Connect urls/views/templates
- [ ] Connect user with article ownership
- [ ] Add 'articles' to INSTALLED APPS
