### ISSUE TITLE
Dev Task # 14 - Django Summernote

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#31]
As a  **developer**, I can **install Django Summernote** so that **I can edit my articles appearance**.

**Acceptance Criteria**
- Successful install of Django Summernote

**Tasks**

- [x] Install Dajngo-Summernote
- [x] Freeze requirements
- [x] Add to INSTALLED APPS
- [x] Adjust admin view in admin.py
- [x] Migrate changes
- [x] Make a test article
