### ISSUE TITLE
Dev Task #4 - Set up Cloudinary

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#4]
As a **developer**, I can **set up a Cloudinary account and connect it to my project** so that **I can upload any images to be stored**.

**Acceptance Criteria**
1. Successful connection between FreeFido and Cloudinary.
2. Successful connection between Cloudinary and Heroku.
3. Configuration of Media and Static files.

**Tasks**
- [x] Add Cloudinary API environment variable to env.py and Heroku
- [x] Set DISABLE_COLLECTSTATIC on Heroku (_remove before deployment_)
- [x] Add Cloudinary libraries to INSTALLED_APPS in settings.py
- [x] In settings.py set Cloudinary as storage for media and static files
