### ISSUE TITLE
Dev Task #5 - Deployment

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#5]
As a **developer**, I can **instruct Django** to **deploy the project successfully**.

**Acceptance Criteria**
1. Inform Django where the templates are stored.
2. Inform Django where the project is being hosted.
3. Successful first deployment.

**Tasks**
- [x] Set up the templates directory in settings.py
- [x] Add Heroku host name into ALLOWED_HOSTS in settings.py
- [x] Create the media, static and templates folders in the top level directory
- [x] Create a Procfile and add project name
- [x] Save, add, commit, push
- [x] Deploy
