### ISSUE TITLE
Dev Task # 6 -Create Database models from ERD

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#6]
As a **developer**, I can **setup my models.py file** to **create the structure of my database tables**.

**Acceptance Criteria**
1. Successfully create FreeFido ERD.
2. Add models to models.py.
3. Import relevant Django/Cloudinary models.

**Tasks** 
- [x] Import Django/Cloudinary models
- [x] Add user model
- [x] Add dog model
- [x] Add booking model
- [x] Add photo model 
- [x] Add feedback model

**Comment by amylour** [comment]
Successful migrations to database 🚀
