### ISSUE TITLE
User Story #1 - Homepage/About template

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido#8]
As a **user**, I would like to **view the websites home page** so that I can **learn about it and the services it offers**.

‌

**Acceptance Criteria**
1. The site is browsable without requiring the user to login.
2. The user can learn about the services from the home page.

**Tasks** 
- [x] Create base template and extend home view template
- [x] Create index.html template for Home/About page with skeleton content
- [x] Connect urls.py

**Comment by amylour** [comment]
- Copied allauth files into templates/allauth 
- Added Tailwind as per Dev Task #25 
- Added Flowbite CDN and basescript.js file
- Added Flowbite header and footer components and edited

**Comment by amylour** [comment]
- Recreated for FreeFido v2, using Bootstrap5
- Included in v2 Sprints
